-- Run this file once in the Supabase SQL Editor for the project:
-- https://cqnovqvmxwmfngupgtov.supabase.co

create table if not exists public.peller_wed_email_registration (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null unique,
  gift text not null check (gift in ('cow','data','cash','available')),
  share_progress integer not null default 0 check (share_progress >= 0),
  share_complete boolean not null default false,
  source_page text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.peller_wed_email_registration enable row level security;

drop policy if exists "Allow public registration inserts" on public.peller_wed_email_registration;
create policy "Allow public registration inserts"
on public.peller_wed_email_registration
for insert
to anon
with check (
  char_length(trim(full_name)) >= 3
  and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
  and gift in ('cow','data','cash','available')
);

drop policy if exists "Allow public registration updates" on public.peller_wed_email_registration;
create policy "Allow public registration updates"
on public.peller_wed_email_registration
for update
to anon
using (true)
with check (
  char_length(trim(full_name)) >= 3
  and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
  and gift in ('cow','data','cash','available')
);

-- No public SELECT or DELETE policy is created.
-- Visitors can register and update progress, but cannot list or delete records.

grant insert, update on table public.peller_wed_email_registration to anon;
grant usage, select on sequence public.peller_wed_email_registration_id_seq to anon;
