-- Run this once in Supabase Dashboard → SQL Editor.
-- Project: Peller-wed email registration

create table if not exists public.peller_wed_email_registration (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null unique,
  gift text not null,
  share_progress integer not null default 0 check (share_progress >= 0),
  share_complete boolean not null default false,
  source_page text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.peller_wed_email_registration enable row level security;

-- Visitors may submit a registration.
drop policy if exists "public can insert registrations" on public.peller_wed_email_registration;
create policy "public can insert registrations"
on public.peller_wed_email_registration
for insert
to anon
with check (
  length(full_name) between 3 and 120
  and length(phone) between 11 and 15
  and position('@' in email) > 1
  and gift in ('cow', 'data', 'cash', 'available')
);

-- Required by the current site so the same email can resume and update progress.
-- No public SELECT or DELETE policy is created.
drop policy if exists "public can update own submitted registration" on public.peller_wed_email_registration;
create policy "public can update own submitted registration"
on public.peller_wed_email_registration
for update
to anon
using (true)
with check (
  length(full_name) between 3 and 120
  and length(phone) between 11 and 15
  and position('@' in email) > 1
  and gift in ('cow', 'data', 'cash', 'available')
  and share_progress >= 0
);

grant insert, update on public.peller_wed_email_registration to anon;
grant usage, select on sequence public.peller_wed_email_registration_id_seq to anon;

-- Keep updated_at current automatically.
create or replace function public.set_peller_wed_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists peller_wed_set_updated_at on public.peller_wed_email_registration;
create trigger peller_wed_set_updated_at
before update on public.peller_wed_email_registration
for each row execute function public.set_peller_wed_updated_at();
